export enum TRANSACTION_TYPE_ENUM {
    EXPENSE = 'expense',
    INCOME = 'income',
    TRANSACTION = 'transaction',
    // REGULAR_EXPENSE = 'regular_expense',
    // REGULAR_INCOME = 'regular_income',
}

export type TransactionType =
    | TRANSACTION_TYPE_ENUM.EXPENSE
    | TRANSACTION_TYPE_ENUM.TRANSACTION
    | TRANSACTION_TYPE_ENUM.INCOME;
// | TRANSACTION_TYPE_ENUM.REGULAR_EXPENSE
// | TRANSACTION_TYPE_ENUM.REGULAR_INCOME
